Repository ConnecTo-FrontEnd/DDD, pull requests merged in 2022-08, with the labels that each got.

#8 네비게이션 메인영역 푸터 일부 마크업 완성
  index.html
Labels: 기능개발

#11 assets 폴더 생성 및 스타일을 위한 이미지 추가
  assets/favicon/android-chrome-192x192.png
  assets/favicon/android-chrome-512x512.png
  assets/favicon/apple-touch-icon.png
  assets/favicon/favicon-16x16.png
  assets/favicon/favicon-32x32.png
  assets/favicon/favicon.ico
  assets/favicon/site.webmanifest
  assets/icon-location/icon-location-a-shape-house.png
  assets/icon-location/icon-location-alien.png
  assets/icon-location/icon-location-artistic-house.png
  assets/icon-location/icon-location-beach.png
  assets/icon-location/icon-location-best-view.png
  assets/icon-location/icon-location-cabin.png
  assets/icon-location/icon-location-camping.png
  assets/icon-location/icon-location-island.png
  assets/icon-location/icon-location-lake-side.png
  assets/icon-location/icon-location-national-park.png
  assets/icon-location/icon-location-north-pole.png
  assets/icon-location/icon-location-pool.png
  assets/icon-location/icon-location-shelter.png
  assets/icon-location/icon-location-small-house.png
  assets/icon-location/icon-location-surfing.png
  assets/icon-location/icon-location-tropical.png
  assets/icon/icon-avatar-filled.png
  assets/icon/icon-filter.png
  assets/icon/icon-globe.png
  assets/icon/icon-globe.svg
  assets/icon/icon-hamburger-menu.png
  assets/icon/icon-hamburger-menu.svg
  assets/icon/icon-heart.png
  assets/icon/icon-right-arrow.png
  assets/icon/icon-search-pink.png
  assets/icon/icon-search-pink.svg
  assets/icon/icon-search-white.png
  assets/icon/icon-search-white.svg
  assets/icon/icon-search.png
  assets/icon/icon-search.svg
  assets/icon/icon-sort.svg
  assets/logo/logo-airbnb.png
  assets/logo/logo-airbnb.svg
Labels: 에셋

#23 노드 패키지 설정
  .gitignore
  .htmlhintrc
  .prettierignore
  .prettierrc.json
  header.html
  index.html
  index.scss
  package-lock.json
  package.json
  styles/base/_default.scss
  styles/base/_index.scss
  styles/themes/_color.scss
  styles/themes/_font.scss
Labels: 환경설정

#28 헤더 영역 스타일 작업 (데스크탑 버전)
  header.html
  image/Airbnb_Logo_Bélo.svg
  index.scss
  package-lock.json
  styles/layout/_header.scss
Labels: 스타일

#25 푸터 스타일링
  styles/layout/_footer.scss
Labels: 스타일

#27 공통 스타일 부분 에러 해결
  .github/PULL_REQUEST_TEMPLATE.md
  styles/themes/_color.scss
  styles/themes/_font.scss
  styles/utils/_a11y.scss
Labels: 스타일

#32 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/-------.md
Labels: 컨벤션

#29 메인 영역 스타일 완성
  main.scss
Labels: 스타일

#31 네비게이션 영역 스타일 완성
  assets/icon-location/icon-location-sprite.png
  navigation.scss
Labels: 스타일

#35 헤더 모바일 스타일링
  header.html
  styles/layout/_header.scss
Labels: 스타일

#34 HTML, CSS 파일 병합 및 누락된 스타일 추가
  header.html
  index.html
  index.scss
  main.scss
  navigation.scss
  styles/utils/_index.scss
Labels: 스타일

#42 배포 환경 설정 및 테스트 배포버전 생성
  .gitignore
  package-lock.json
  package.json
  postcss.config.js
  public/assets/favicon/android-chrome-192x192.png
  public/assets/favicon/android-chrome-512x512.png
  public/assets/favicon/apple-touch-icon.png
  public/assets/favicon/favicon-16x16.png
  public/assets/favicon/favicon-32x32.png
  public/assets/favicon/favicon.ico
  public/assets/favicon/site.webmanifest
  public/assets/icon-location/icon-location-a-shape-house.png
  public/assets/icon-location/icon-location-alien.png
  public/assets/icon-location/icon-location-artistic-house.png
  public/assets/icon-location/icon-location-beach.png
  public/assets/icon-location/icon-location-best-view.png
  public/assets/icon-location/icon-location-cabin.png
  public/assets/icon-location/icon-location-camping.png
  public/assets/icon-location/icon-location-island.png
  public/assets/icon-location/icon-location-lake-side.png
  public/assets/icon-location/icon-location-national-park.png
  public/assets/icon-location/icon-location-north-pole.png
  public/assets/icon-location/icon-location-pool.png
  public/assets/icon-location/icon-location-shelter.png
  public/assets/icon-location/icon-location-small-house.png
  public/assets/icon-location/icon-location-sprite.png
  public/assets/icon-location/icon-location-surfing.png
  public/assets/icon-location/icon-location-tropical.png
  public/assets/icon/icon-avatar-filled.png
  public/assets/icon/icon-filter.png
  public/assets/icon/icon-globe.png
  public/assets/icon/icon-globe.svg
  public/assets/icon/icon-hamburger-menu.png
  public/assets/icon/icon-hamburger-menu.svg
  public/assets/icon/icon-heart.png
  public/assets/icon/icon-right-arrow.png
  public/assets/icon/icon-search-pink.png
  public/assets/icon/icon-search-pink.svg
  public/assets/icon/icon-search-white.png
  public/assets/icon/icon-search-white.svg
  public/assets/icon/icon-search.png
  public/assets/icon/icon-search.svg
  public/assets/icon/icon-sort.svg
  public/assets/logo/logo-airbnb.png
  public/assets/logo/logo-airbnb.svg
  public/index.css
  public/index.html
  styles/base/_normalize.scss
Labels: 환경설정, 리뷰 불필요, 배포

#43 HTML, CSS 최적화 진행
  index.html
  index.scss
  styles/base/_normalize.scss
Labels: 리팩토링

#44 네비게이션 이미지 수정 및 메인 영역 이미지 추가
  assets/icon-location/real-icon-location-sprite.png
  assets/icon/icon-star.svg
  index.html
  index.scss
Labels: 스타일

#45 크로스 브라우징 지원
  assets/logo/logo-airbnb-m.svg
  assets/logo/logo-airbnb.svg
  index.html
  styles/layout/_header.scss
Labels: 리팩토링

#47 refactor: Skeleton UI 해결
  index.scss
Labels: 스타일, 리팩토링

#48 Public에 누락된 이미지 에셋 추가
  public/assets/icon-location/real-icon-location-sprite.png
  public/assets/icon/icon-star.svg
  public/assets/logo/logo-airbnb-m.svg
  public/index.css
Labels: 리뷰 불필요
